# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-controller
{{- end }}
