# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- range $index, $version := .Values.image.versions }}
{{- $versionsHash := sha256sum (toYaml $.Values.image.versions) }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" $ }}-{{ $version.schema | replace "." "-" }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    schema-version: {{ $version.schema }}
    {{- if $version.default }}
    default-schema: "true"
    {{- end }}
spec:
  replicas: {{ $.Values.autoscaling.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" $ | nindent 6 }}
      schema-version: {{ $version.schema }}
  template:
    metadata:
      annotations:
        versions-hash: "{{ $versionsHash }}"
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" $ | nindent 8 }}
        schema-version: {{ $version.schema }}
        {{- if $version.default }}
        default-schema: "true"
        {{- end }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $version.server }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
          {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
            - name: SCHEMA_VERSIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-schema-versions
                  key: versions
            - name: SCHEMA_PATH
              value: /{{ $version.schema }}
          ports:
            - name: http
              containerPort: {{ $.Values.config.server_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            {{- with $.Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml $.Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml $.Values.affinity | nindent 8 }}
      volumes:
        {{- with $.Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
