# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: locator.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'locator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlocator.proto\x12\tapi.proto\"\x98\x02\n\x07Locator\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x16.api.proto.LocatorTypeR\x04type\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12\x45\n\x0b\x61nnotations\x18\x03 \x03(\x0b\x32#.api.proto.Locator.AnnotationsEntryR\x0b\x61nnotations\x12\x17\n\x04size\x18\x04 \x01(\x04H\x00R\x04size\x88\x01\x01\x12\x1b\n\x06\x64igest\x18\x05 \x01(\tH\x01R\x06\x64igest\x88\x01\x01\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x07\n\x05_sizeB\t\n\x07_digest*\xbf\x01\n\x0bLocatorType\x12\x1c\n\x18LOCATOR_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17LOCATOR_TYPE_HELM_CHART\x10\x01\x12\x1d\n\x19LOCATOR_TYPE_DOCKER_IMAGE\x10\x02\x12\x1f\n\x1bLOCATOR_TYPE_PYTHON_PACKAGE\x10\x03\x12\x1c\n\x18LOCATOR_TYPE_SOURCE_CODE\x10\x04\x12\x17\n\x13LOCATOR_TYPE_BINARY\x10\x05\x42~\n\rcom.api.protoB\x0cLocatorProtoP\x01Z\x1agithub.com/agntcy/oasf/api\xa2\x02\x03\x41PX\xaa\x02\tApi.Proto\xca\x02\tApi\\Proto\xe2\x02\x15\x41pi\\Proto\\GPBMetadata\xea\x02\nApi::Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'locator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.api.protoB\014LocatorProtoP\001Z\032github.com/agntcy/oasf/api\242\002\003APX\252\002\tApi.Proto\312\002\tApi\\Proto\342\002\025Api\\Proto\\GPBMetadata\352\002\nApi::Proto'
  _globals['_LOCATOR_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_LOCATOR_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_LOCATORTYPE']._serialized_start=312
  _globals['_LOCATORTYPE']._serialized_end=503
  _globals['_LOCATOR']._serialized_start=29
  _globals['_LOCATOR']._serialized_end=309
  _globals['_LOCATOR_ANNOTATIONSENTRY']._serialized_start=227
  _globals['_LOCATOR_ANNOTATIONSENTRY']._serialized_end=289
# @@protoc_insertion_point(module_scope)
