# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

localDeploy: true

image:
  repository: ghcr.io/agntcy/oasf-server
  versions:
    - server: latest
      schema: 0.3.1
      default: true
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: localhost
  tls: []
  service:
    type: NodePort

service:
  type: NodePort

env:
  HOST: localhost
  URL_PORT: 8080
  SCHEMA_DIR: /schema

volumes:
  - name: schema
    hostPath:
      path: /schema
      type: Directory

volumeMounts:
  - name: schema
    mountPath: /schema
