version: "3.9"
services:
  oasf-server:
    build: .
    ports: 
      - "${OASF_SERVER_PORT:-8080}:8080"
    working_dir: /oasf-server
    environment:
      - "SCHEMA_DIR=/app/schema"
    volumes:
        - "./:/oasf-server:z"
        - "${SCHEMA_PATH:-../oasf-schema}:/app/schema:z"

  oasf-elixir:
    image: "elixir:${ELIXIR_VERSION:-1.14-alpine}"
    working_dir: /oasf-server
    entrypoint: /docker-entrypoint-dev.sh
    command: echo # dummy command
    environment:
      - "SCHEMA_DIR=/app/schema"
      - "MIX_HOME=/oasf-server/.mix"
    volumes:
        - "./:/oasf-server:z"
        - "${SCHEMA_PATH:-../oasf-schema}:/app/schema:z"
        - "./docker-entrypoint-dev.sh:/docker-entrypoint-dev.sh"
