# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: record.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import skill_pb2 as skill__pb2
import locator_pb2 as locator__pb2
import extension_pb2 as extension__pb2
import signature_pb2 as signature__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecord.proto\x12\tapi.proto\x1a\x0bskill.proto\x1a\rlocator.proto\x1a\x0f\x65xtension.proto\x1a\x0fsignature.proto\"\xcf\x04\n\x06Record\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n\x07version\x18\x03 \x01(\tR\x07version\x12%\n\x0eschema_version\x18\x64 \x01(\tR\rschemaVersion\x12 \n\x0b\x64\x65scription\x18\x04 \x01(\tR\x0b\x64\x65scription\x12\x18\n\x07\x61uthors\x18\x05 \x03(\tR\x07\x61uthors\x12\x44\n\x0b\x61nnotations\x18\x01 \x03(\x0b\x32\".api.proto.Record.AnnotationsEntryR\x0b\x61nnotations\x12\x1d\n\ncreated_at\x18\x06 \x01(\tR\tcreatedAt\x12(\n\x06skills\x18\x07 \x03(\x0b\x32\x10.api.proto.SkillR\x06skills\x12.\n\x08locators\x18\x08 \x03(\x0b\x32\x12.api.proto.LocatorR\x08locators\x12\x34\n\nextensions\x18\t \x03(\x0b\x32\x14.api.proto.ExtensionR\nextensions\x12\x32\n\tsignature\x18\n \x01(\x0b\x32\x14.api.proto.SignatureR\tsignature\x12\x33\n\x13previous_record_cid\x18\x63 \x01(\tH\x00R\x11previousRecordCid\x88\x01\x01\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x16\n\x14_previous_record_cidB}\n\rcom.api.protoB\x0bRecordProtoP\x01Z\x1agithub.com/agntcy/oasf/api\xa2\x02\x03\x41PX\xaa\x02\tApi.Proto\xca\x02\tApi\\Proto\xe2\x02\x15\x41pi\\Proto\\GPBMetadata\xea\x02\nApi::Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.api.protoB\013RecordProtoP\001Z\032github.com/agntcy/oasf/api\242\002\003APX\252\002\tApi.Proto\312\002\tApi\\Proto\342\002\025Api\\Proto\\GPBMetadata\352\002\nApi::Proto'
  _globals['_RECORD_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_RECORD_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_RECORD']._serialized_start=90
  _globals['_RECORD']._serialized_end=681
  _globals['_RECORD_ANNOTATIONSENTRY']._serialized_start=595
  _globals['_RECORD_ANNOTATIONSENTRY']._serialized_end=657
# @@protoc_insertion_point(module_scope)
