# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Helm Chart Release

on:
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
      release_tag:
        required: true
        type: string
        description: "Release tag for the Helm chart."
      helm-version:
        required: false
        default: "3.12.1"
        type: string
        description: "Helm version to use."

jobs:
  chart:
    name: Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: notused
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Setup Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814  # v4.2.0
        with:
          version: ${{ inputs.helm-version }}

      - name: Helm update dependencies
        shell: bash
        run: helm dependency update install/charts/oasf

      - name: Helm lint
        shell: bash
        run: helm lint install/charts/oasf --with-subcharts

      - name: Set chart name
        id: chart-name
        shell: bash
        run: echo "value=${{ github.event.repository.name }}" >> "$GITHUB_OUTPUT"

      - name: Helm package
        shell: bash
        run: |
          helm package install/charts/oasf --dependency-update --version ${{ inputs.release_tag }}

      - name: Helm push to GHCR OCI registry
        shell: bash
        run: |
          echo "🚧 Pushing ${{ inputs.release_tag }} to GHCR OCI registry"
          helm push ${{ steps.chart-name.outputs.value }}-${{ inputs.release_tag }}.tgz oci://${{ inputs.image_repo }}/oasf/helm-charts
